name: Run Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Check maven version
        run: mvn --version
      - name: Set DP_M2_HOME
        run: echo "DP_M2_HOME=$(mvn -v | grep 'Maven home' | cut -d' ' -f3-)" >> $GITHUB_ENV
      - name: Build with Maven
        env:
          DP_MVN_REPO: ~/.m2
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          flags: unittests
          fail_ci_if_error: false

#      - name: Upload war file to github releases
#        uses: AButler/upload-release-assets@v2.0
#        with:
#          files: 'target/drop-project.war'
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          release-tag: 0.9.3